site_name: AcompanhaLegis Docs
dev_addr: '0.0.0.0:8080'

theme:
  name: material
  language: pt
  font:
    text: Ubuntu
    code: Ubuntu Mono

repo_name: AcompanhaLegis/docs
repo_url: https://github.com/AcompanhaLegis/docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AcompanhaLegis
