site_name: AcompanhaLegis Docs
dev_addr: '0.0.0.0:8080'

nav:
  - Home: index.md
  - Sobre:
    - Informações Globais: about/about.md
    - Contribuir: about/contributing.md
  - Banco de dados:
    - PostgreSQL: database/postgres.md
  - Django:
    - O Framework: django/django.md
    - Python: django/python.md
  - MKDOCS: mkdocs.md

theme:
  name: material
  language: pt
  font:
    text: Ubuntu
    code: Ubuntu Mono

repo_name: AcompanhaLegis/docs
repo_url: https://github.com/AcompanhaLegis/docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AcompanhaLegis
